# The URL the site will be built for
base_url = "https://baptisteesteban.github.io"

# Whether to automatically compile all Sass files in the sass directory
compile_sass = true

# Whether to build a search index to be used later on by a JavaScript library
build_search_index = false

[markdown]
# Whether to do syntax highlighting
# Theme can be customised by setting the `highlight_theme` variable to a theme supported by Zola
# highlight_code = true

[extra]
# Put all your custom variables here
title = "Baptiste Esteban"

[extra.card]
firstname = "Baptiste"
lastname = "Esteban"
picture_path = "baptiste_esteban_photo.png" # File must be in the `static` directory
extra_title = "PhD"
position = "Associate Professor"
company = "EPITA Research Laboratory"
company_website = "https://www.lre.epita.fr"
company_street = "14-16 rue Voltaire"
company_city = "94270 Le Kremlin-Bicêtre"
company_country = "FRANCE"
email = "baptiste.esteban@epita.fr"
linkedin = "https://www.linkedin.com/in/baptisteesteban"
github = "https://github.com/baptisteesteban"
orcid = "https://orcid.org/0000-0002-6477-7666"
scholar = "https://scholar.google.com/citations?user=oMFBuyEAAAAJ&hl=fr&oi=ao"
